/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagement;

import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        DoctorsTeam = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();
        LoadingLabel = new javax.swing.JLabel();
        HospitalName = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BackgroundPanel.setBackground(new java.awt.Color(0, 255, 255));
        BackgroundPanel.setPreferredSize(new java.awt.Dimension(900, 500));
        BackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DoctorsTeam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/Assets/Doctor_image3.jpg"))); // NOI18N
        DoctorsTeam.setText("jLabel1");
        BackgroundPanel.add(DoctorsTeam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 600, 400));

        LoadingBar.setForeground(new java.awt.Color(255, 255, 255));
        BackgroundPanel.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 900, 10));

        LoadingLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        LoadingLabel.setForeground(new java.awt.Color(255, 255, 255));
        LoadingLabel.setText("Loading...");
        BackgroundPanel.add(LoadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        HospitalName.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        HospitalName.setForeground(new java.awt.Color(255, 255, 255));
        HospitalName.setText("CHURCH ROAD HOSPITAL");
        BackgroundPanel.add(HospitalName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        LoadingValue.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        LoadingValue.setForeground(new java.awt.Color(255, 255, 255));
        LoadingValue.setText("0%");
        BackgroundPanel.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, 30, -1));

        BackgroundImage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/Assets/Background4.jpg"))); // NOI18N
        BackgroundImage.setText("jLabel1");
        BackgroundImage.setPreferredSize(new java.awt.Dimension(900, 500));
        BackgroundPanel.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SplashScreen sp = new SplashScreen();
        sp.setVisible(true);
        
        try{  Thread.sleep(100); 
            for(int i=0;i<=100;i++){
                  sp.LoadingValue.setText(i +"%");
               Thread.sleep(100);
                sp.LoadingValue.setText(i +"%");
                
                if(i==10){
                    sp.LoadingLabel.setText("Turning on Modules...");
                }
                 if(i==20){
                    sp.LoadingLabel.setText("Loading on Modules...");
                }
                  if(i==50){
                    sp.LoadingLabel.setText("Connecting to Database...");
                }
                   if(i==70){
                    sp.LoadingLabel.setText("Connection Successful !!");
                }
                    if(i==80){
                    sp.LoadingLabel.setText("Launching Aplication...");
                }
                    sp.LoadingBar.setValue(i);
            }
        }
        catch (InterruptedException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JLabel DoctorsTeam;
    private javax.swing.JLabel HospitalName;
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingLabel;
    private javax.swing.JLabel LoadingValue;
    // End of variables declaration//GEN-END:variables
}
